[package]
name = "Kglance"
version = "0.1.0"
edition = "2024"

[dependencies]
syntect = { version = "5", default-features = false, features = ["default-onig"] }
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "webp", "gif", "bmp"] }
resvg = "0.43"
lopdf = "0.34"
zip = "2"
tar = "0.4"
sevenz-rust = "0.6"
slint = "1"
zbus = "5"

[build-dependencies]
slint-build = "1"

[profile.release]
lto = true
opt-level = "z"
strip = true
