use kglance::core::layout_engine::{LayoutConfig, LogicalDocument, TextLayoutEngine, WrapMode};

#[test]
fn test_no_wrap_layout() {
    let doc = LogicalDocument::from_text("Line 1\nLine 2\nLine 3");
    let config = LayoutConfig {
        viewport_width: 100.0,
        font_size: 14.0,
        tab_width: 4,
        wrap_mode: WrapMode::NoWrap,
    };
    let layout = TextLayoutEngine::compute(&doc, &config);
    assert_eq!(layout.visual_lines.len(), 3);
    assert_eq!(layout.visual_lines[0].line_number, Some(1));
    assert_eq!(layout.visual_lines[1].line_number, Some(2));
    assert_eq!(layout.visual_lines[2].line_number, Some(3));
}

#[test]
fn test_word_wrap_line_numbers() {
    let long_line = "A".repeat(50);
    let doc = LogicalDocument::from_text(&format!("Short 1\n{}\nShort 3", long_line));
    let config = LayoutConfig {
        viewport_width: 100.0,
        font_size: 14.0,
        tab_width: 4,
        wrap_mode: WrapMode::CharWrap(12),
    };
    let layout = TextLayoutEngine::compute(&doc, &config);

    assert!(layout.visual_lines.len() > 3);
    assert_eq!(layout.visual_lines[0].line_number, Some(1));
    assert_eq!(layout.visual_lines[1].line_number, Some(2));
    assert_eq!(layout.visual_lines[2].line_number, None);
    assert_eq!(layout.visual_lines.last().unwrap().line_number, Some(3));
}

#[test]
fn test_gutter_misalignment_when_editor_wraps() {
    // When using a plain string "1\n2\n3" alongside a soft-wrapping widget,
    // the visual lines count of editor (4) exceeds the gutter line count (3).
    let content_text = "Short line 1\nThis is a long line that wraps across multiple visual lines when displayed in editor\nShort line 3";
    let doc = LogicalDocument::from_text(content_text);

    // Gutter generated by simple 1..N string:
    let naive_gutter_lines: Vec<&str> = (1..=doc.lines.len())
        .map(|n| match n {
            1 => "1",
            2 => "2",
            _ => "3",
        })
        .collect();

    // Actual visual layout needed for wrapped editor:
    let config = LayoutConfig {
        viewport_width: 100.0,
        font_size: 14.0,
        tab_width: 4,
        wrap_mode: WrapMode::CharWrap(30),
    };
    let visual_doc = TextLayoutEngine::compute(&doc, &config);

    // Assert that naive static gutter has FEWER lines than actual visual lines needed,
    // proving why static 1..N gutter causes vertical misalignment when text wraps!
    assert!(visual_doc.visual_lines.len() > naive_gutter_lines.len());
    assert_eq!(visual_doc.visual_lines.len(), 5); // 1 + 3 wrapped lines + 1 = 5
    assert_eq!(naive_gutter_lines.len(), 3);
}

#[test]
fn test_json_raw_editor_selectable_and_line_count() {
    let json_str = r#"{"name": "kglance", "version": 1}"#;
    let doc = LogicalDocument::from_text(json_str);
    let editor_content: iced::widget::text_editor::Content =
        iced::widget::text_editor::Content::with_text(json_str);

    assert_eq!(doc.lines.len(), 1);
    assert_eq!(editor_content.text(), json_str);
}
