import { HorizontalBox } from "std-widgets.slint";
import { NavButton } from "./common.slint";

export component NavBar inherits HorizontalBox {
    in-out property<bool> has-prev;
    in-out property<bool> has-next;
    callback prev-clicked();
    callback next-clicked();

    spacing: 4px;
    padding: 4px;
    horizontal-stretch: 1;
    alignment: center;

    NavButton { icon-text: "◀"; is-enabled: has-prev; clicked => { prev-clicked(); } }
    Rectangle { width: 16px; }
    NavButton { icon-text: "▶"; is-enabled: has-next; clicked => { next-clicked(); } }
}
