pub(super) fn latex_cmd_to_unicode(cmd: &str) -> Option<&'static str> {
    match cmd {
        // Arrows
        "\\Leftrightarrow" | "\\iff" => Some("⇔"),
        "\\Rightarrow" | "\\implies" => Some("⇒"),
        "\\Leftarrow" => Some("⇐"),
        "\\leftrightarrow" => Some("↔"),
        "\\rightarrow" | "\\to" => Some("→"),
        "\\leftarrow" | "\\gets" => Some("←"),
        "\\mapsto" => Some("↦"),
        "\\uparrow" => Some("↑"),
        "\\downarrow" => Some("↓"),

        // Logic & Sets
        "\\forall" => Some("∀"),
        "\\exists" => Some("∃"),
        "\\nexists" => Some("∄"),
        "\\neg" | "\\lnot" => Some("¬"),
        "\\land" => Some("∧"),
        "\\lor" => Some("∨"),
        "\\notin" => Some("∉"),
        "\\in" => Some("∈"),
        "\\ni" | "\\owns" => Some("∋"),
        "\\emptyset" | "\\varnothing" => Some("∅"),
        "\\subseteq" => Some("⊆"),
        "\\subset" => Some("⊂"),
        "\\supseteq" => Some("⊇"),
        "\\supset" => Some("⊃"),
        "\\setminus" => Some("\\"),
        "\\cup" => Some("∪"),
        "\\cap" => Some("∩"),

        // Relations & Comparisons
        "\\approx" => Some("≈"),
        "\\equiv" => Some("≡"),
        "\\sim" => Some("∼"),
        "\\simeq" => Some("≃"),
        "\\cong" => Some("≅"),
        "\\neq" | "\\ne" => Some("≠"),
        "\\leq" | "\\le" => Some("≤"),
        "\\geq" | "\\ge" => Some("≥"),
        "\\ll" => Some("≪"),
        "\\gg" => Some("≫"),
        "\\propto" => Some("∝"),
        "\\perp" | "\\bot" => Some("⊥"),
        "\\parallel" => Some("∥"),
        "\\mid" => Some("|"),

        // Arithmetic & Operations
        "\\times" => Some("×"),
        "\\div" => Some("÷"),
        "\\pm" => Some("±"),
        "\\mp" => Some("∓"),
        "\\cdot" => Some("·"),
        "\\circ" => Some("°"),
        "\\oplus" => Some("⊕"),
        "\\ominus" => Some("⊖"),
        "\\otimes" => Some("⊗"),
        "\\odot" => Some("⊙"),
        "\\ast" | "\\star" => Some("★"),

        // Calculus & Analysis
        "\\infty" => Some("∞"),
        "\\partial" => Some("∂"),
        "\\nabla" => Some("∇"),
        "\\sum" => Some("∑"),
        "\\prod" => Some("∏"),
        "\\oiint" => Some("∯"),
        "\\iiint" => Some("∭"),
        "\\iint" => Some("∬"),
        "\\oint" => Some("∮"),
        "\\int" => Some("∫"),
        "\\hbar" => Some("ℏ"),
        "\\ell" => Some("ℓ"),
        "\\dots" | "\\ldots" => Some("…"),
        "\\cdots" => Some("⋯"),
        "\\vdots" => Some("⋮"),
        "\\ddots" => Some("⋱"),

        // Math functions
        "\\exp" => Some("exp"),
        "\\ln" => Some("ln"),
        "\\log" => Some("log"),
        "\\sin" => Some("sin"),
        "\\cos" => Some("cos"),
        "\\tan" => Some("tan"),
        "\\arcsin" => Some("arcsin"),
        "\\arccos" => Some("arccos"),
        "\\arctan" => Some("arctan"),
        "\\det" => Some("det"),
        "\\arg" => Some("arg"),
        "\\max" => Some("max"),
        "\\min" => Some("min"),

        // Greek uppercase
        "\\Gamma" => Some("Γ"),
        "\\Delta" => Some("Δ"),
        "\\Theta" => Some("Θ"),
        "\\Lambda" => Some("Λ"),
        "\\Xi" => Some("Ξ"),
        "\\Pi" => Some("Π"),
        "\\Sigma" => Some("Σ"),
        "\\Upsilon" => Some("Υ"),
        "\\Phi" => Some("Φ"),
        "\\Psi" => Some("Ψ"),
        "\\Omega" => Some("Ω"),

        // Greek lowercase
        "\\alpha" => Some("α"),
        "\\beta" => Some("β"),
        "\\gamma" => Some("γ"),
        "\\delta" => Some("δ"),
        "\\epsilon" | "\\varepsilon" => Some("ε"),
        "\\zeta" => Some("ζ"),
        "\\eta" => Some("η"),
        "\\theta" | "\\vartheta" => Some("θ"),
        "\\iota" => Some("ι"),
        "\\kappa" => Some("κ"),
        "\\lambda" => Some("λ"),
        "\\mu" => Some("μ"),
        "\\nu" => Some("ν"),
        "\\xi" => Some("ξ"),
        "\\pi" | "\\varpi" => Some("π"),
        "\\rho" | "\\varrho" => Some("ρ"),
        "\\sigma" | "\\varsigma" => Some("σ"),
        "\\tau" => Some("τ"),
        "\\upsilon" => Some("υ"),
        "\\phi" | "\\varphi" => Some("φ"),
        "\\chi" => Some("χ"),
        "\\psi" => Some("ψ"),
        "\\omega" => Some("ω"),

        // Delimiters and helpers
        "\\therefore" => Some("∴"),
        "\\because" => Some("∵"),
        "\\angle" => Some("∠"),
        "\\triangle" => Some("△"),
        "\\langle" => Some("⟨"),
        "\\rangle" => Some("⟩"),
        "\\qquad" => Some("  "),
        "\\quad" => Some(" "),
        "\\left" => Some(""),
        "\\right" => Some(""),
        _ => None,
    }
}
